"""empty message

Revision ID: 465345bdc26c
Revises: 045da8c8dff2
Create Date: 2023-02-26 23:07:05.255458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465345bdc26c'
down_revision = '045da8c8dff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
